services:
  app:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${IMAGE_TAG}
    pull_policy: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SERVER_HOST_FRONT: https://newsintelligent.site
      SPRING_APPLICATION_JSON: >
        {"server":{"host":{"front":"${SERVER_HOST_FRONT}"}}}
    ports:
      - "8080:8080"
    restart: always