services:
  app:
    image: ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPOSITORY}:${IMAGE_TAG}
    container_name: app
    pull_policy: always

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: prod

      # Actuator
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,info
      MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"

      # Micrometer 이슈 우회
      MANAGEMENT_METRICS_BINDERS_PROCESSOR_ENABLED: "false"

      # JWT
      SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      SECURITY_JWT_EXPIRATION_ACCESS: ${JWT_EXPIRATION_ACCESS:-14400000}

      SERVER_HOST_FRONT: https://newsintelligent.site

      # JVM/Pool 안전장치
      JAVA_TOOL_OPTIONS: >-
        -XX:MaxRAMPercentage=60.0
        -XX:InitialRAMPercentage=60.0
        -XX:+ExitOnOutOfMemoryError
        -XX:+HeapDumpOnOutOfMemoryError
        -XX:HeapDumpPath=/tmp/heap.hprof
      SERVER_TOMCAT_THREADS_MAX: "100"
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: "10"

    ports:
      - "8081:8080"

    restart: unless-stopped