name: "Bug Report"
description: "버그 리포트"
title: "Bug: 00 발생"
labels: "bug"
body:
  - type: input
    attributes:
      label: "🐞 문제 요약"
      placeholder: "어떤 문제가 발생했는지 간단하게 설명해주세요."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "🔍 버그 설명"
      placeholder: |
        - 어떤 페이지 또는 기능에서 발생했나요?
        - 어떤 상황에서 문제가 발생하나요?
        - 관련된 로그, 메세지, 스크린샷이 있다면 첨부해주세요.
    validations:
      required: true

  - type: input
    attributes:
      label: "🌟 예상 결과"
      placeholder: "기능/버그 수정 후 기대되는 결과를 작성해주세요."
    validations:
      required: false

  - type: input
    attributes:
      label: "📆 기한"
      description: "예상 수정 완료 날짜"
      placeholder: "2025-01-01"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "📝 메모"
      placeholder: "참고 자료 링크나 부가적으로 필요한 자원이 있다면 메모하세요"