name: News Intelligent CI

on:
  push:
  pull_request:
    branches:
      - develop

jobs:
  build:
    # ubuntu 버전 지정
    runs-on: ubuntu-22.04

    steps:
      # GitHub 레포지토리 checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # DockerHub 로그인
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

      # Docker 이미지 빌드 및 푸시
      - name: Build and Push Docker image
        run: |
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:latest .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:latest